package com.seckill.dao;

import com.seckill.dos.KillDO;

public interface KillDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    int insert(KillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    int insertSelective(KillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    KillDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    int updateByPrimaryKeySelective(KillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kill_activity
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    int updateByPrimaryKey(KillDO record);

    KillDO selectByItemId(Integer itemId);
}