package com.seckill.dos;

import java.math.BigDecimal;
import java.util.Date;

public class KillDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.kill_name
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private String killName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.kill_item_price
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private BigDecimal killItemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.item_id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.start_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kill_activity.end_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.id
     *
     * @return the value of kill_activity.id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.id
     *
     * @param id the value for kill_activity.id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.kill_name
     *
     * @return the value of kill_activity.kill_name
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public String getKillName() {
        return killName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.kill_name
     *
     * @param killName the value for kill_activity.kill_name
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setKillName(String killName) {
        this.killName = killName == null ? null : killName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.kill_item_price
     *
     * @return the value of kill_activity.kill_item_price
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public BigDecimal getKillItemPrice() {
        return killItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.kill_item_price
     *
     * @param killItemPrice the value for kill_activity.kill_item_price
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setKillItemPrice(BigDecimal killItemPrice) {
        this.killItemPrice = killItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.item_id
     *
     * @return the value of kill_activity.item_id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.item_id
     *
     * @param itemId the value for kill_activity.item_id
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.start_date
     *
     * @return the value of kill_activity.start_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.start_date
     *
     * @param startDate the value for kill_activity.start_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kill_activity.end_date
     *
     * @return the value of kill_activity.end_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kill_activity.end_date
     *
     * @param endDate the value for kill_activity.end_date
     *
     * @mbg.generated Sat Feb 01 15:31:35 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}